package exceptions

import "errors"

var UserVerifyError = errors.New("user_verify_error")
